# Create note
POST https://pl583b1me1.execute-api.us-east-1.amazonaws.com/dev/notes
content-type: application/json
Authorization: eyJraWQiOiJiTWdKRldTbU91ZGd6RlRjRlp5RTgyeXNoVElwVkQyVTlIbnJsVnh6dWhrPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiYmlaUGRhNkZSVkQ4MXhLZFlVa0dHdyIsInN1YiI6ImRjMzI3YzFjLTExZGQtNGEyNi04YjU1LTA2MzkxODY2OWNjYyIsImF1ZCI6IjduNmx0NHZhbGduZGUxOG1yZDQzdGl1M2g0IiwiZXZlbnRfaWQiOiJlODBhYmUwZC1hN2M0LTRkMDYtYmI3ZS03MjExM2E2MmQyYzciLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY5OTg2NjE5MCwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfdnVrelBITHJ5IiwiY29nbml0bzp1c2VybmFtZSI6Indhcml0IiwiZXhwIjoxNjk5ODY5NzkwLCJpYXQiOjE2OTk4NjYxOTAsImp0aSI6IjQyYWQ5NjU5LTljMjctNDI5OC05MDJlLWE5YzUxMzc2MjQxYSJ9.Ce1jenLwBaUrr4lQyPc80DYjXM4VVHguxymMK23SvA41q_kPEuBFH0WeIZ0Roy6l-A34g5MyGjS8W_lJS3SgG3dgmLOrHUCFpTshSDuBqYnz4pWPNyRiJYBJg2v_II8RbSDMHymq31MMsLuhT_fSVnWpUGulwiUcxQ9NLD8vgvB9lUz_UwnPmD8TXna_JV6dPilBGFhGitT9gh7AKeu9EUIyZs22BTyHlpZe9bfyEnL-vZxQp5pTBSdCe_oXs4TOqhHfSLQNozKAHnPbj4oicMtjX07HlO0w7Yi3MTOglLInBQMe6u8f81G7DT8pcJZPGGT3vxAD37T0cYzSPHaE7g

{
    "id": "2",
    "title": "Note title",
    "body": "This is the body"
}

### Update note
PUT https://jpfbj5jw3g.execute-api.us-east-1.amazonaws.com/dev/notes/1
content-type: application/json

{
    "title": "Updated title",
    "body": "This is a new body"
}

### Delete note
DELETE https://jpfbj5jw3g.execute-api.us-east-1.amazonaws.com/dev/notes/2
content-type: application/json

### Get all notes
GET https://pl583b1me1.execute-api.us-east-1.amazonaws.com/dev/notes
Authorization: eyJraWQiOiJiTWdKRldTbU91ZGd6RlRjRlp5RTgyeXNoVElwVkQyVTlIbnJsVnh6dWhrPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiYmlaUGRhNkZSVkQ4MXhLZFlVa0dHdyIsInN1YiI6ImRjMzI3YzFjLTExZGQtNGEyNi04YjU1LTA2MzkxODY2OWNjYyIsImF1ZCI6IjduNmx0NHZhbGduZGUxOG1yZDQzdGl1M2g0IiwiZXZlbnRfaWQiOiJlODBhYmUwZC1hN2M0LTRkMDYtYmI3ZS03MjExM2E2MmQyYzciLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY5OTg2NjE5MCwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfdnVrelBITHJ5IiwiY29nbml0bzp1c2VybmFtZSI6Indhcml0IiwiZXhwIjoxNjk5ODY5NzkwLCJpYXQiOjE2OTk4NjYxOTAsImp0aSI6IjQyYWQ5NjU5LTljMjctNDI5OC05MDJlLWE5YzUxMzc2MjQxYSJ9.Ce1jenLwBaUrr4lQyPc80DYjXM4VVHguxymMK23SvA41q_kPEuBFH0WeIZ0Roy6l-A34g5MyGjS8W_lJS3SgG3dgmLOrHUCFpTshSDuBqYnz4pWPNyRiJYBJg2v_II8RbSDMHymq31MMsLuhT_fSVnWpUGulwiUcxQ9NLD8vgvB9lUz_UwnPmD8TXna_JV6dPilBGFhGitT9gh7AKeu9EUIyZs22BTyHlpZe9bfyEnL-vZxQp5pTBSdCe_oXs4TOqhHfSLQNozKAHnPbj4oicMtjX07HlO0w7Yi3MTOglLInBQMe6u8f81G7DT8pcJZPGGT3vxAD37T0cYzSPHaE7g

### Login Cognito
GET https://serverlessnotesdemo.auth.us-east-1.amazoncognito.com/login?response_type=token&client_id=7v318fdn7ieekipodm0eea4m1o&redirect_uri=http://localhost:3000