version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing serverless CLI
      - npm i -g serverless@2
      - cd notes
      - echo Installing npm dependencies of notes service
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Packaging the service
      - serverless deploy --stage dev
artifacts:
  files:
    - notes/my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'notes/node_modules/**/*'
